site_name: FastEdgy
site_description: Base that makes web application development simple and fast with FastAPI and Edgy ORM
site_author: Krafter SAS
site_url: https://krafterio.github.io/fastedgy

repo_name: krafterio/fastedgy
repo_url: https://github.com/krafterio/fastedgy
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Krafter SAS

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: custom
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/krafterio/fastedgy
      name: Github
  generator: false

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: krafterio
      repo: fastedgy
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - FastEdgy: index.md
  - Features:
    - features/index.md
    - Core Features:
      - Container Service:
        - Overview: features/container-service/overview.md
        - Getting Started: features/container-service/getting-started.md
        - User Guide: features/container-service/guide.md
        - Advanced Usage: features/container-service/advanced.md
        - Technical Details: features/container-service/technical.md
      - Queued Tasks:
        - Overview: features/queued-tasks/overview.md
        - Getting Started: features/queued-tasks/getting-started.md
        - User Guide: features/queued-tasks/guide.md
        - Advanced Usage: features/queued-tasks/advanced.md
        - Technical Details: features/queued-tasks/technical.md
