site_name: FastEdgy
site_description: Base that makes web application development simple and fast with FastAPI and Edgy ORM
site_author: Krafter SAS
site_url: https://krafterio.github.io/fastedgy

repo_name: krafterio/fastedgy
repo_url: https://github.com/krafterio/fastedgy
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 Krafter SAS

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: custom
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/krafterio/fastedgy
      name: Github
  generator: false

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: krafterio
      repo: fastedgy
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Features:
    - features/index.md
    - API Features:
      - API Routes Generator:
        - Overview: features/api-routes/overview.md
      - Query Builder:
        - Overview: features/query-builder/overview.md
      - Fields Selector:
        - Overview: features/fields-selector/overview.md
      - Metadata Generator:
        - Overview: features/metadata-generator/overview.md
    - ORM Features:
      - ORM Extensions:
        - Overview: features/orm-extensions/overview.md
      - Database Migration:
        - Overview: features/database-migration/overview.md
    - Core Features:
      - Container Service:
        - Overview: features/container-service/overview.md
        - Getting Started: features/container-service/getting-started.md
        - User Guide: features/container-service/guide.md
        - Advanced Usage: features/container-service/advanced.md
        - Technical Details: features/container-service/technical.md
      - Queued Tasks:
        - Overview: features/queued-tasks/overview.md
        - Getting Started: features/queued-tasks/getting-started.md
        - User Guide: features/queued-tasks/guide.md
        - Advanced Usage: features/queued-tasks/advanced.md
        - Technical Details: features/queued-tasks/technical.md
      - CLI:
        - Overview: features/cli/overview.md
      - Internationalization:
        - Overview: features/i18n/overview.md
      - Multi Tenant:
        - Overview: features/multi-tenant/overview.md
    - Services:
      - Email:
        - Overview: features/email/overview.md
      - Storage:
        - Overview: features/storage/overview.md
    - Miscellaneous Features:
      - Authentication:
        - Overview: features/auth/overview.md
  - Vue.js:
    - Getting Started: vue/getting-started.md
    - Basic Usage: vue/basic-usage.md
    - Troubleshooting: vue/troubleshooting.md
    - Core Features:
      - Bus:
        - Overview: vue/bus/overview.md
        - User Guide: vue/bus/guide.md
      - Fetcher:
        - Overview: vue/fetcher/overview.md
        - User Guide: vue/fetcher/guide.md
        - Advanced Features: vue/fetcher/advanced.md
    - Vue Integration:
      - Fetcher Plugin:
        - Overview: vue/fetcher-plugin/overview.md
        - Setup Guide: vue/fetcher-plugin/setup.md
      - Fetcher Directive:
        - Overview: vue/fetcher-directive/overview.md
        - User Guide: vue/fetcher-directive/guide.md
      - Metadata Store:
        - Overview: vue/metadata-store/overview.md
        - User Guide: vue/metadata-store/guide.md
        - Examples & Ideas: vue/metadata-store/examples.md
      - Auth Store:
        - Overview: vue/auth-store/overview.md
        - User Guide: vue/auth-store/guide.md
        - Advanced Features: vue/auth-store/advanced.md
    - Utils:
      - Validations:
        - Overview: vue/validations/overview.md
        - User Guide: vue/validations/guide.md
      - Routers:
        - Overview: vue/routers/overview.md
        - User Guide: vue/routers/guide.md
      - Logger:
        - Overview: vue/logger/overview.md
        - Setup Guide: vue/logger/setup.md
  - MCP: mcp.md
  - About: about.md
  - Contributing: contributing.md
