# Copyright Krafter SAS <developer@krafter.io>
# MIT License (see LICENSE file).

from edgy.exceptions import (
    CommandEnvironmentError,
    DatabaseNotConnectedWarning,
    DuplicateRecordError,
    EdgyException,
    FieldDefinitionError,
    FileOperationError,
    ForeignKeyBadConfigured,
    ImproperlyConfigured,
    InvalidStorageError,
    MarshallFieldDefinitionError,
    ModelCollisionError,
    ModelReferenceError,
    ModelSchemaError,
    MultipleObjectsReturned,
    ObjectNotFound,
    QuerySetError,
    RelationshipIncompatible,
    RelationshipNotFound,
    SchemaError,
    SignalError,
    SuspiciousFileOperation,
    TableBuildError,
)

__all__ = [
    "CommandEnvironmentError",
    "DatabaseNotConnectedWarning",
    "DuplicateRecordError",
    "EdgyException",
    "FieldDefinitionError",
    "FileOperationError",
    "ForeignKeyBadConfigured",
    "ImproperlyConfigured",
    "InvalidStorageError",
    "MarshallFieldDefinitionError",
    "ModelCollisionError",
    "ModelReferenceError",
    "ModelSchemaError",
    "MultipleObjectsReturned",
    "ObjectNotFound",
    "QuerySetError",
    "RelationshipIncompatible",
    "RelationshipNotFound",
    "SchemaError",
    "SignalError",
    "SuspiciousFileOperation",
    "TableBuildError",
]
