# Copyright Krafter SAS <developer@krafter.io>
# MIT License (see LICENSE file).

from collections.abc import Generator
from typing import Any


class _RelatedQuerySet[T]:
    def __await__(self) -> Generator[Any, Any, list[T]]: ...
    def __aiter__(self) -> "_RelatedQuerySet[T]": ...
    async def __anext__(self) -> T: ...
    def __getattr__(self, name: str) -> Any: ...


class Many[T = Any]:
    def all(self, clear_cache: bool = False) -> _RelatedQuerySet[T]: ...
    async def add(self, child: T) -> T | None: ...
    async def remove(self, child: T | None = None) -> None: ...
    async def create(self, *args: Any, **kwargs: Any) -> T | None: ...
    def stage(self, *children: T) -> None: ...
    async def add_many(self, *children: T) -> list[T | None]: ...
    async def remove_many(self, *children: T) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


__all__ = ["Many"]
