name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Setup cache
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Configure cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Deploy documentation
        run: |
          # Fetch the gh-pages branch to avoid conflicts
          git fetch origin gh-pages --depth=1 2>/dev/null || true

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Deployment of a tagged version (eg: 0.2.0 -> 0.2)
            VERSION=${GITHUB_REF#refs/tags/}
            MAJOR_MINOR=$(echo $VERSION | cut -d. -f1-2)
            uv run mike deploy --push --update-aliases $MAJOR_MINOR latest
            uv run mike set-default --push latest
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            # Deployment of the main branch -> 'dev' version
            uv run mike deploy --push dev
          fi
